// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.TronEvent = (function(superClass) {
    extend(TronEvent, superClass);

    function TronEvent() {
      return TronEvent.__super__.constructor.apply(this, arguments);
    }

    return TronEvent;

  })(Backbone.Model);

  window.MinimalEventListEntryView = (function(superClass) {
    extend(MinimalEventListEntryView, superClass);

    function MinimalEventListEntryView() {
      return MinimalEventListEntryView.__super__.constructor.apply(this, arguments);
    }

    MinimalEventListEntryView.prototype.tagName = "tr";

    MinimalEventListEntryView.prototype.template = _.template("<td><%= dateFromNow(time) %></td>\n<td>\n  <span class=\"label <%= level %>\">\n    <%= name %>\n  </span>\n</td>");

    MinimalEventListEntryView.prototype.render = function() {
      this.$el.html(this.template(this.model.attributes));
      makeTooltips(this.$el);
      return this;
    };

    return MinimalEventListEntryView;

  })(Backbone.View);

}).call(this);
