version: 2
jobs:
  build:
    docker:
      - image: golang:1.6.4
    working_directory: /go/src/github.com/raravena80/tron-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.05.0-ce

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t  raravena80/tron-docker:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push raravena80/tron-docker:$TAG
